# Formação 2 - Machine Learning Development in Python
---
*João Brazuna*

## Apresentação dos Conjuntos de Dados
---
Nesta formação, usaremos maioritariamente dois conjuntos de dados reais e de acesso livre:

### [**Titanic**](https://www.kaggle.com/competitions/titanic/data)
<img src="images/Titanic.jpg" width="200">

Os dados do Titanic contêm informação real sobre os passageiros e a indicação se o passageiro sobreviveu ou não, que é aquilo que se pretende que seja previsto.

|  ID  | Variável    | Descrição                                 | Valores                                                              |
| ---: | :----       | :----                                     | :---                                                                 |
|    0 | PassengerId | ID do Passageiro                          | 1, 2, 3,..., 891                                                     |
|    1 | Survival    | Indicatriz da Sobrevivência do Passageiro | 1 se o passageiro tiver sobrevivido, 0 caso contrário                |
|    2 | Pclass      | Classe Económica do Passageiro            | 1 para 1ª classe, 2 para 2ª classe e 3 para passageiros de 3ª classe |
|    3 | Name        | Nome do Passageiro                        | Nome do passageiro, incluindo o título (Mr., Miss., Mrs.,...)        |
|    4 | Sex         | Género do Passageiro                      | "male" ou "female"                                                   |
|    5 | Age         | Idade do Passageiro em Anos               | 0.42, 0.67, 0.75, 0.83, 0.92, 1, 2,...                               |
|    6 | SibSp       | Número de Irmãos e Cônjuges no Titanic    | 0, 1, 2,...                                                          |
|    7 | Parch       | Número de Pais e Filhos no Titanic        | 0, 1, 2,...                                                          |
|    8 | Ticket      | Número do Bilhete                         | "A/5 21171", "PC 17599", "STON/O2. 3101282",...                      |
|    9 | Fare        | Preço do Bilhete                          | 0, 4.0125, 5, 6.2375,...                                             |
|   10 | Cabin       | Camarote onde ficou o Passageiro          | "C85", "C123", "E46",...                                             |
|   11 | Embarked    | Porto onde o Passageiro Embarcou          | "C" para Cherbourg, "Q" para Queenstown ou "S" para Southampton      |

### [**Desempenho dos Alunos**](https://archive.ics.uci.edu/ml/datasets/student%2Bperformance)
<img src="images/PTMAT.jpg" width="200">

Contém dados sobre alunos de duas escolas portuguesas, incluindo as suas notas das disciplinas de Português e Matemática nos 3 períodos. O objectivo é prever a nota final de cada aluno numa das disciplinas.


| ID  | Variável    | Descrição                                 | Valores            |
| ---: | :---- | :---- | :--- |
|  1 | school     | Escola do Aluno                          | "GP" - Gabriel Pereira ou "MS" - Mousinho da Silveira|
|  2 | sex        | Género do Aluno                          | "F" - feminino ou "M" - masculino |
|  3 | age        | Idade do Aluno                           | De 15 a 22 |
|  4 | address    | Tipo de Localidade de Residência         | "U" - urbana ou "R" - rural |
|  5 | famsize    | Tamanho da Família                       | "LE3" - menor ou igual a 3 ou "GT3" - maior que 3 |
|  6 | Pstatus    | Estado de Coabitação dos Pais            | "T" - juntos ou "A" - separados |
|  7 | Medu       | Educação da Mãe                          | 0 - Nenhuma,  1 - Educação Primária (4º Ano), 2 – 5º ao 9º Ano, 3 – Educação Secundária ou 4 – Educação Superior |
|  8 | Fedu       | Educação do Pai                          | 0 - Nenhuma,  1 - Educação Primária (4º Ano), 2 – 5º ao 9º Ano, 3 – Educação Secundária ou 4 – Educação Superior |
|  9 | Mjob       | Emprego da Mãe                           | "teacher" - Professora, "health" - Área da Saúde, "services" - Serviços Públicos ou Administrativos, "at_home" - Doméstica ou "other" - Outros |
| 10 | Fjob       | Emprego do Pai                           | "teacher" - Professor, "health" - Área da Saúde, "services" - Serviços Públicos ou Administrativos, "at_home" - Doméstico ou "other" - Outros |
| 11 | reason     | Razão para ter escolhido a escola        | "home" - Perto de casa, "reputation" - Reputação da Escola, "course" - Preferência pelo curso ou "other" - Outros |
| 12 | guardian   | Encarregado de Educação                  | "mother" - Mãe, "father" - Pai ou "other" - Outro |
| 13 | traveltime | Tempo de Viagem Casa - Escola            | 1 - <15 min., 2 - 15 a 30 min., 3 - 30 min. a 1 hora, ou 4 - >1 hora |
| 14 | studytime  | Tempo de Estudo por Semana               | 1 - <2 horas, 2 - 2 a 5 horas, 3 - 5 a 10 horas, ou 4 - >10 horas |
| 15 | failures   | Número de Chumbos Anteriores             | n se 1<=n<3, caso contrário 4 |
| 16 | schoolsup  | Suporte Educacional Extra                | "yes" - Sim, ou "no" - Não |
| 17 | famsup     | Suporte Educacional por parte da Família | "yes" - Sim, ou "no" - Não |
| 18 | paid       | Aulas Pagas Extra da Disciplina          | "yes" - Sim, ou "no" - Não |
| 19 | activities | Actividades Extra-curriculares           | "yes" - Sim, ou "no" - Não |
| 20 | nursery    | Frequentou a Pré-Primária                | "yes" - Sim, ou "no" - Não |
| 21 | higher     | Pretende seguir para o Ensino Superior   | "yes" - Sim, ou "no" - Não |
| 22 | internet   | Tem acesso à Internet em Casa            | "yes" - Sim, ou "no" - Não |
| 23 | romantic   | Encontra-se numa Relação Amorosa         | "yes" - Sim, ou "no" - Não |
| 24 | famrel     | Qualidade das Relações Familiares        | De 1 - Muito Má a 5 - Muito Boa |
| 25 | freetime   | Tempo Livre depois da Escola             | De 1 - Muito Pouco a 5 - Muito |
| 26 | goout      | Saídas com Amigos                        | De 1 - Pouco Frequentes a 5 - Muito Frequentes |
| 27 | Dalc       | Consumo de Álcool durante a Semana       | De 1 - Pouco Frequente a 5 - Muito Frequente |
| 28 | Walc       | Consumo de Álcool ao Fim-de-Semana       | De 1 - Pouco Frequente a 5 - Muito Frequente |
| 29 | health     | Estado de Saúde Actual                   | De 1 - Muito Mau a 5 - Muito Bom |
| 30 | absences   | Número de Faltas à Escola                | De 0 a 93 |
| **31** | **G1** | Nota Final da Disciplina no 1º Período   | De 0 a 20 |
| **31** | **G2** | Nota Final da Disciplina no 2º Período   | De 0 a 20 |
| **32** | **G3** | Nota Final da Disciplina no 3º Período   | De 0 a 20, **variável a prever** |

*Nota Adicional*: há 382 estudantes comuns a ambos os conjuntos de dados. Estes estudantes podem ser identificados procurando atributos idênticos que os caracterizem.

## Importar Pacotes Necessários
---

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression, LogisticRegression

import statsmodels.api as sm

## Exemplo de Regressão Linear Simples
---

In [22]:
X = pd.DataFrame({'1': [1] * 12,
                  'X': [32, 48, 72, 64, 48, 16, 40, 48, 48, 24, 80, 56]})
X

1   X
0   1  32
1   1  48
2   1  72
3   1  64
4   1  48
5   1  16
6   1  40
7   1  48
8   1  48
9   1  24
10  1  80
11  1  56

In [23]:
y = pd.Series([230, 262, 323, 298, 255, 199, 248, 279, 267, 214, 359, 305])
y

0     230
1     262
2     323
3     298
4     255
5     199
6     248
7     279
8     267
9     214
10    359
11    305
dtype: int64

In [24]:
np.matmul((X.T).values, X.values)

array([[   12,   576],
       [  576, 31488]], dtype=int64)

In [26]:
np.linalg.inv(np.matmul((X.T).values, X.values))

array([[ 6.83333333e-01, -1.25000000e-02],
       [-1.25000000e-02,  2.60416667e-04]])

In [27]:
np.matmul((X.T).values, y.values)

array([  3239, 164752], dtype=int64)

In [29]:
np.matmul(np.linalg.inv(np.matmul((X.T).values, X.values)), np.matmul((X.T).values, y.values))

array([153.91666667,   2.41666667])

## Carregar os Dados
---

In [2]:
titanic_df = pd.read_csv('data/Titanic.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
students_df = pd.read_csv('data/students.csv')
students_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
365     MS   F   19       R     GT3       T     2     3  services     other   
366     MS   F   18       U     LE3       T     3     1   teacher  services   
367     MS   F   18       U     GT3       T     1     1     other     other   
368     MS   M   17       U     LE3       T     3     1  services  services   
369     MS   M   18       R     LE3       T     3     2  services     other   

     ... paid_por activities_por Dalc_por Walc_por  health_por absences_por  \
0    ...       no             no        1        1           3            4   
1    ...       no             no        1        1           3            2   
2    ...       no             no        2        3           3            6   
3    ...       no            yes        1        1           5            0   
4    ...       no             no        1        2           5            0   
..   ...      ...            ...      ...      ...         ...          ...   
365  ...       no            yes        1        2           5            4   
366  ...       no             no        1        1           1            4   
367  ...       no            yes        1        1           5            6   
368  ...       no             no        3        4           2            6   
369  ...       no             no        3        4           5            4   

    G1_por  G2_por  G3_por  studytime  
0        0      11      11          4  
1        9      11      11          4  
2       12      13      12          4  
3       14      14      14          6  
4       11      13      13          4  
..     ...     ...     ...        ...  
365     10      11      10          6  
366     15      15      16          4  
367     11      12       9          4  
368     10      10      10          2  
369     10      11      11          2  

[370 rows x 47 columns]